//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICommonService")]
public interface ICommonService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetData", ReplyAction="http://tempuri.org/ICommonService/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetData", ReplyAction="http://tempuri.org/ICommonService/GetDataResponse")]
    System.Threading.Tasks.Task<string> GetDataAsync(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetServerDateTime", ReplyAction="http://tempuri.org/ICommonService/GetServerDateTimeResponse")]
    System.DateTime GetServerDateTime();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetServerDateTime", ReplyAction="http://tempuri.org/ICommonService/GetServerDateTimeResponse")]
    System.Threading.Tasks.Task<System.DateTime> GetServerDateTimeAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Login", ReplyAction="http://tempuri.org/ICommonService/LoginResponse")]
    string Login(string UserName, string Password, string DataSetID, string DataSetDBName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Login", ReplyAction="http://tempuri.org/ICommonService/LoginResponse")]
    System.Threading.Tasks.Task<string> LoginAsync(string UserName, string Password, string DataSetID, string DataSetDBName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Logout", ReplyAction="http://tempuri.org/ICommonService/LogoutResponse")]
    string Logout(string UserName, string Password, string DataSetID, string DataSetDBName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Logout", ReplyAction="http://tempuri.org/ICommonService/LogoutResponse")]
    System.Threading.Tasks.Task<string> LogoutAsync(string UserName, string Password, string DataSetID, string DataSetDBName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/ForceLogout", ReplyAction="http://tempuri.org/ICommonService/ForceLogoutResponse")]
    string ForceLogout(string UserName, string Password, string DataSetID, string DataSetDBName, string validationTicket);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/ForceLogout", ReplyAction="http://tempuri.org/ICommonService/ForceLogoutResponse")]
    System.Threading.Tasks.Task<string> ForceLogoutAsync(string UserName, string Password, string DataSetID, string DataSetDBName, string validationTicket);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/TestConnection", ReplyAction="http://tempuri.org/ICommonService/TestConnectionResponse")]
    bool TestConnection(byte[] validationTicket);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/TestConnection", ReplyAction="http://tempuri.org/ICommonService/TestConnectionResponse")]
    System.Threading.Tasks.Task<bool> TestConnectionAsync(byte[] validationTicket);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetCommonDataDict", ReplyAction="http://tempuri.org/ICommonService/GetCommonDataDictResponse")]
    string GetCommonDataDict(string Account, string strDataTypes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetCommonDataDict", ReplyAction="http://tempuri.org/ICommonService/GetCommonDataDictResponse")]
    System.Threading.Tasks.Task<string> GetCommonDataDictAsync(string Account, string strDataTypes);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICommonServiceChannel : ICommonService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CommonServiceClient : System.ServiceModel.ClientBase<ICommonService>, ICommonService
{
    
    public CommonServiceClient()
    {
    }
    
    public CommonServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CommonServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CommonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CommonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public System.Threading.Tasks.Task<string> GetDataAsync(int value)
    {
        return base.Channel.GetDataAsync(value);
    }
    
    public System.DateTime GetServerDateTime()
    {
        return base.Channel.GetServerDateTime();
    }
    
    public System.Threading.Tasks.Task<System.DateTime> GetServerDateTimeAsync()
    {
        return base.Channel.GetServerDateTimeAsync();
    }
    
    public string Login(string UserName, string Password, string DataSetID, string DataSetDBName)
    {
        return base.Channel.Login(UserName, Password, DataSetID, DataSetDBName);
    }
    
    public System.Threading.Tasks.Task<string> LoginAsync(string UserName, string Password, string DataSetID, string DataSetDBName)
    {
        return base.Channel.LoginAsync(UserName, Password, DataSetID, DataSetDBName);
    }
    
    public string Logout(string UserName, string Password, string DataSetID, string DataSetDBName)
    {
        return base.Channel.Logout(UserName, Password, DataSetID, DataSetDBName);
    }
    
    public System.Threading.Tasks.Task<string> LogoutAsync(string UserName, string Password, string DataSetID, string DataSetDBName)
    {
        return base.Channel.LogoutAsync(UserName, Password, DataSetID, DataSetDBName);
    }
    
    public string ForceLogout(string UserName, string Password, string DataSetID, string DataSetDBName, string validationTicket)
    {
        return base.Channel.ForceLogout(UserName, Password, DataSetID, DataSetDBName, validationTicket);
    }
    
    public System.Threading.Tasks.Task<string> ForceLogoutAsync(string UserName, string Password, string DataSetID, string DataSetDBName, string validationTicket)
    {
        return base.Channel.ForceLogoutAsync(UserName, Password, DataSetID, DataSetDBName, validationTicket);
    }
    
    public bool TestConnection(byte[] validationTicket)
    {
        return base.Channel.TestConnection(validationTicket);
    }
    
    public System.Threading.Tasks.Task<bool> TestConnectionAsync(byte[] validationTicket)
    {
        return base.Channel.TestConnectionAsync(validationTicket);
    }
    
    public string GetCommonDataDict(string Account, string strDataTypes)
    {
        return base.Channel.GetCommonDataDict(Account, strDataTypes);
    }
    
    public System.Threading.Tasks.Task<string> GetCommonDataDictAsync(string Account, string strDataTypes)
    {
        return base.Channel.GetCommonDataDictAsync(Account, strDataTypes);
    }
}
